framework:
    messenger:
        transports:
#             amqp: '%env(MESSENGER_TRANSPORT_DSN)%'
             amqp: 'enqueue://default'

        routing:
            # Route your messages to the transports
             'App\Message\CreatePdf': amqp
